import axios from "axios";

const data = {
  header: "Программист",
  description:
    "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ducimus est repudiandae deleniti eligendi saepe, quos cumque aliquid aperiam possimus dignissimos eum porro beatae voluptatibus cupiditate. Saepe distinctio itaque odit quam?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ducimus est repudiandae deleniti eligendi saepe, quos cumque aliquid aperiam possimus dignissimos eum porro beatae voluptatibus cupiditate. Saepe distinctio itaque odit quam?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ducimus est repudiandae deleniti eligendi saepe, quos cumque aliquid aperiam possimus dignissimos eum porro beatae voluptatibus cupiditate. Saepe distinctio itaque odit quam?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ducimus est repudiandae deleniti eligendi saepe, quos cumque aliquid aperiam possimus dignissimos eum porro beatae voluptatibus cupiditate. Saepe distinctio itaque odit quam?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ducimus est repudiandae deleniti eligendi saepe, quos cumque aliquid aperiam possimus dignissimos eum porro beatae voluptatibus cupiditate. Saepe distinctio itaque odit quam?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ducimus est repudiandae deleniti eligendi saepe, quos cumque aliquid aperiam possimus dignissimos eum porro beatae voluptatibus cupiditate. Saepe distinctio itaque odit quam?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ducimus est repudiandae deleniti eligendi saepe, quos cumque aliquid aperiam possimus dignissimos eum porro beatae voluptatibus cupiditate. Saepe distinctio itaque odit quam?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ducimus est repudiandae deleniti eligendi saepe, quos cumque aliquid aperiam possimus dignissimos eum porro beatae voluptatibus cupiditate. Saepe distinctio itaque odit quam?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ducimus est repudiandae deleniti eligendi saepe, quos cumque aliquid aperiam possimus dignissimos eum porro beatae voluptatibus cupiditate. Saepe distinctio itaque odit quam?",
  type: "it",
};
axios.post("http://localhost:3000/api/admin/vacancy", data);
